import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    API_PORT: z.ZodOptional<z.ZodNumber>;
    API_HOST: z.ZodOptional<z.ZodString>;
    NEXT_PUBLIC_API_BASE_URL: z.ZodOptional<z.ZodString>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    DISCORD_BOT_TOKEN: z.ZodOptional<z.ZodString>;
    DISCORD_CLIENT_ID: z.ZodOptional<z.ZodString>;
    DISCORD_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    DISCORD_REDIRECT_URI: z.ZodOptional<z.ZodString>;
    TURNSTILE_SECRET_KEY: z.ZodOptional<z.ZodString>;
    HCAPTCHA_SECRET_KEY: z.ZodOptional<z.ZodString>;
    UPLOAD_STORAGE_ROOT: z.ZodOptional<z.ZodString>;
    ACCOUNT_LINKING_ENABLED: z.ZodOptional<z.ZodString>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    MICROSOFT_CLIENT_ID: z.ZodOptional<z.ZodString>;
    MICROSOFT_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    MICROSOFT_REDIRECT_URI: z.ZodOptional<z.ZodString>;
    NAVER_CLIENT_ID: z.ZodOptional<z.ZodString>;
    NAVER_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    NAVER_REDIRECT_URI: z.ZodOptional<z.ZodString>;
    OBSERVABILITY_ENDPOINT: z.ZodOptional<z.ZodString>;
    OBSERVABILITY_API_KEY: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV?: "development" | "test" | "production";
    API_PORT?: number;
    API_HOST?: string;
    NEXT_PUBLIC_API_BASE_URL?: string;
    REDIS_URL?: string;
    DISCORD_BOT_TOKEN?: string;
    DISCORD_CLIENT_ID?: string;
    DISCORD_CLIENT_SECRET?: string;
    DISCORD_REDIRECT_URI?: string;
    TURNSTILE_SECRET_KEY?: string;
    HCAPTCHA_SECRET_KEY?: string;
    UPLOAD_STORAGE_ROOT?: string;
    ACCOUNT_LINKING_ENABLED?: string;
    SENTRY_DSN?: string;
    MICROSOFT_CLIENT_ID?: string;
    MICROSOFT_CLIENT_SECRET?: string;
    MICROSOFT_REDIRECT_URI?: string;
    NAVER_CLIENT_ID?: string;
    NAVER_CLIENT_SECRET?: string;
    NAVER_REDIRECT_URI?: string;
    OBSERVABILITY_ENDPOINT?: string;
    OBSERVABILITY_API_KEY?: string;
}, {
    NODE_ENV?: "development" | "test" | "production";
    API_PORT?: number;
    API_HOST?: string;
    NEXT_PUBLIC_API_BASE_URL?: string;
    REDIS_URL?: string;
    DISCORD_BOT_TOKEN?: string;
    DISCORD_CLIENT_ID?: string;
    DISCORD_CLIENT_SECRET?: string;
    DISCORD_REDIRECT_URI?: string;
    TURNSTILE_SECRET_KEY?: string;
    HCAPTCHA_SECRET_KEY?: string;
    UPLOAD_STORAGE_ROOT?: string;
    ACCOUNT_LINKING_ENABLED?: string;
    SENTRY_DSN?: string;
    MICROSOFT_CLIENT_ID?: string;
    MICROSOFT_CLIENT_SECRET?: string;
    MICROSOFT_REDIRECT_URI?: string;
    NAVER_CLIENT_ID?: string;
    NAVER_CLIENT_SECRET?: string;
    NAVER_REDIRECT_URI?: string;
    OBSERVABILITY_ENDPOINT?: string;
    OBSERVABILITY_API_KEY?: string;
}>;
type EnvSchema = z.infer<typeof envSchema>;
type NumericEnvKey = {
    [Key in keyof EnvSchema]: EnvSchema[Key] extends number | undefined ? Key : never;
}[keyof EnvSchema];
export declare class ConfigService {
    private readonly env;
    constructor(source?: NodeJS.ProcessEnv);
    get<Key extends keyof EnvSchema>(key: Key, fallback?: EnvSchema[Key]): NonNullable<EnvSchema[Key]>;
    getOptional<Key extends keyof EnvSchema>(key: Key): EnvSchema[Key] | undefined;
    getNumber(key: NumericEnvKey, fallback?: number): number;
}
export {};
