upstream minewiki_web {
  server 127.0.0.1:4311;
}

upstream minewiki_api {
  server 127.0.0.1:3000;
}

server {
  listen 80;
  server_name minewiki.kr www.minewiki.kr;

  client_max_body_size 128m;

  location = /api/health {
    proxy_pass http://minewiki_api/api/health;
    include proxy_params;
  }

  location /api/ {
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://minewiki_api;
    include proxy_params;
  }

  location /cdn/ {
    alias /var/www/MineWiki/apps/cdn/public/;
    access_log off;
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
  }

  location /uploads/ {
    alias /var/www/MineWiki/apps/cdn/storage/;
    access_log off;
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
  }

  location / {
    proxy_pass http://minewiki_web;
    include proxy_params;
  }
}
