map $uri $minewiki_upstream {
  default wiki;
  ~^/servers(/|$) web;
  ~^/api(/|$) api;
  ~^/cdn(/|$) cdn;
  ~^/verify(/|$) api;
  ~^/account/minecraft(/|$) api;
}

upstream minewiki_wiki {
  server 127.0.0.1:3015;
}

upstream minewiki_web {
  server 127.0.0.1:4311;
}

upstream minewiki_api {
  server 127.0.0.1:3000;
}

upstream minewiki_cdn {
  server 127.0.0.1:4321;
}

server {
  listen 80;
  server_name minewiki.kr www.minewiki.kr;

  location /servers {
    proxy_pass http://minewiki_web;
    include proxy_params;
  }

  location /api {
    proxy_pass http://minewiki_api;
    include proxy_params;
  }

  location /cdn {
    proxy_pass http://minewiki_cdn;
    include proxy_params;
  }

  location /verify {
    proxy_pass http://minewiki_api;
    include proxy_params;
  }

  location /account/minecraft {
    proxy_pass http://minewiki_api;
    include proxy_params;
  }

  location / {
    proxy_pass http://minewiki_wiki;
    include proxy_params;
  }
}
