module.exports = {
  apps: [
    {
      name: 'voteweb-api',
      cwd: '/var/www/VoteWeb',
      script: 'npm',
      args: '--prefix apps/api run start',
      env: {
        NODE_ENV: 'production',
        API_HOST: '127.0.0.1',
        API_PORT: '4310',
        REDIS_URL: 'redis://127.0.0.1:6379',
        DATABASE_URL: 'mysql://root:g2g21941@127.0.0.1:3306/creepervote',
        DATABASE_POOL_MIN: '2',
        DATABASE_POOL_MAX: '30',
        DATABASE_CONN_TIMEOUT_MS: '5000',
        CLAIM_DATABASE_URL: 'mysql://root:g2g21941@127.0.0.1:3306/issue_table',
        TURNSTILE_SECRET_KEY: '0x4AAAAAACeLq0bLjJF16arv_3Q6Dinu9hw',
        NEXT_PUBLIC_TURNSTILE_SITE_KEY: '0x4AAAAAACeLqyiV_YNxkx2v',
        HCAPTCHA_SECRET_KEY: '',
        NEXT_PUBLIC_HCAPTCHA_SITE_KEY: '',
        OBSERVABILITY_ENDPOINT: 'https://lunaf.kr/api/observability',
        OBSERVABILITY_API_KEY: '',
      },
    },
    {
      name: 'voteweb-web',
      cwd: '/var/www/VoteWeb/apps/web',
      script: 'npm',
      args: 'run start',
      env: {
        NODE_ENV: 'production',
        PORT: '4311',
        HOSTNAME: '127.0.0.1',
        NEXT_PUBLIC_API_BASE_URL: 'https://lunaf.kr/api',
        NEXT_PUBLIC_SITE_URL: 'https://lunaf.kr',
      },
    },
    {
      name: 'voteweb-worker',
      cwd: '/var/www/VoteWeb',
      script: 'apps/worker/dist/apps/worker/src/index.js',
      env: {
        NODE_ENV: 'production',
        REDIS_URL: 'redis://127.0.0.1:6379',
        DATABASE_URL: 'mysql://root:g2g21941@127.0.0.1:3306/creepervote',
        CLAIM_DATABASE_URL: 'mysql://root:g2g21941@127.0.0.1:3306/issue_table',
        SERVER_PING_ALLOW_IPV6: 'true',
        OBSERVABILITY_ENDPOINT: 'https://lunaf.kr/api/observability',
        OBSERVABILITY_API_KEY: '',
      },
    },
  ],
};
